const auth = require('./auth')
const {resolve, basename} = require('path')
const {readFileSync} = require('fs')
const {Signale, fatal} = require('signale')
const cb = require('clipboardy')

const log = new Signale({interactive: true})

module.exports = async (filePath, {public = false, html = false}) => {
  try {
    const github = await auth()
    const files = filePath.map(path => {
      const name = basename(path)
      const content = readFileSync(resolve(process.cwd(), path), 'utf8')
      return {name, content}
    }).reduce((acc, {name, content}) => {
      return {
        ...acc,
        [name]: {
          content
        }
      }
    }, {})
    log.pending('upload to gist...')
    const result = await github.gists.create({
      description: 'data generated by https://github.com/chitacan/xprt.',
      public,
      files
    })
    .then(d => d.data)

    if (html) {
      log.success(result.html_url)
    } else {
      Object.keys(result.files)
        .map(filename => {
          return {name: filename, raw_url: result.files[filename].raw_url}
        })
        .forEach(({name, raw_url}, i) => {
          if (i === 0) {
            cb.writeSync(raw_url)
            console.log(`${name}: ${raw_url} (copied)`)
          } else {
            console.log(`${name}: ${raw_url}`)
          }
        })
    }
  } catch (err) {
    fatal(err)
  }
}
